### ISSUE TITLE
RINEX OBS Header "TIME OF FIRST OBS"

### ISSUE THREAD

**Issue by markusbradke** [wlcable/GeoStar_GNSS_Bin2RINEX#1]
Header Label 'TIME OF FIRST OBS' in RINEX observation file is shifted 1 character to the left

**Comment by wlcable** [comment]
Can you give an example? In my testing it looks correct....
[RINEX_OBS_Header_Ex.txt](https://github.com/wlcable/GeoStar_GNSS_Bin2RINEX/files/5820611/RINEX_OBS_Header_Ex.txt)

**Comment by markusbradke** [comment]
Header label indication is correct now

**Comment by markusbradke** [comment]
Header label indication is correct now
